### ISSUE TITLE
soga如何配置多个节点？

### ISSUE THREAD

**Issue by yggcwx** [bbs3223474/LNMP-V2Ray-Trojan-Backend-Config#1]
请问：soga的配置文件，好像是一个节点一套配置（因为有节点ID）？那么，该如何配置多个节点？

**Comment by bbs3223474** [comment]
没办法，soga的工作方式基本决定一个服务器一个节点。
当然我也没深入研究，说不定有其他方法可以实现。

**Comment by yggcwx** [comment]
> 没办法，soga的工作方式基本决定一个服务器一个节点。 当然我也没深入研究，说不定有其他方法可以实现。

多谢指点！
